[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "clusteredheatmap"
version = "1.0.0"
authors = [
  { name="Joris Funk", email="joris.funk@student.hpi.uni-potsdam.de" },
]
description = "Tools for hierarchical clustering and clustered heatmaps / clustergrams"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "numpy>=2.3.5",
  "pandas>=2.3.3",
  "plotly>=6.4.0",
  "scipy>=1.16.3",
  "nandist>=0.12.0",
  "scikit-learn>=1.7.2",
  "distinctipy>=1.3.4",
]

[project.urls]
Source = "https://github.com/jorisfu/clusteredheatmap"
Issues = "https://github.com/jorisfu/clusteredheatmap/issues"
Documentation = "https://clusteredheatmap.readthedocs.io"
